import { AspectRatioOption, LutPreset, SoundEffect, TextPreset } from './types';

export const ASPECT_RATIOS: AspectRatioOption[] = [
  {
    value: '16:9',
    label: '16:9 Landscape',
    sublabel: 'YouTube, TV, Presentations',
    ratio: 16 / 9,
    iconName: 'Tv',
    width: 1280,
    height: 720,
  },
  {
    value: '9:16',
    label: '9:16 Vertical',
    sublabel: 'TikTok, Reels, Shorts',
    ratio: 9 / 16,
    iconName: 'Smartphone',
    width: 720,
    height: 1280,
  },
  {
    value: '1:1',
    label: '1:1 Square',
    sublabel: 'Instagram Feed, Square',
    ratio: 1,
    iconName: 'Square',
    width: 1080,
    height: 1080,
  },
  {
    value: '4:5',
    label: '4:5 Portrait',
    sublabel: 'Instagram Portrait Feed',
    ratio: 4 / 5,
    iconName: 'RectangleVertical',
    width: 1080,
    height: 1350,
  },
  {
    value: '21:9',
    label: '21:9 Ultrawide',
    sublabel: 'Cinematic Anamorphic',
    ratio: 21 / 9,
    iconName: 'Film',
    width: 1680,
    height: 720,
  },
];

export const SAMPLE_VIDEOS = [
  {
    id: 'sample-video-1',
    name: 'Scenic Coastal Waves',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=300&q=80',
    duration: 15,
    category: 'Nature',
  },
  {
    id: 'sample-video-2',
    name: 'Urban Cyber City Lights',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=300&q=80',
    duration: 15,
    category: 'Urban',
  },
  {
    id: 'sample-video-3',
    name: 'Creative Tech Motion',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=300&q=80',
    duration: 18,
    category: 'Technology',
  },
  {
    id: 'sample-video-4',
    name: 'Sunset Sky Timelapse',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=300&q=80',
    duration: 15,
    category: 'Aesthetic',
  },
];

export const SOUND_EFFECTS: SoundEffect[] = [
  { id: 'sfx-whoosh', name: 'Cinematic Whoosh', category: 'impact', duration: 0.8, type: 'whoosh' },
  { id: 'sfx-ding', name: 'Success Bell Chime', category: 'ui', duration: 1.2, type: 'ding' },
  { id: 'sfx-pop', name: 'Snappy Bubble Pop', category: 'foley', duration: 0.3, type: 'pop' },
  { id: 'sfx-camera', name: 'Camera Shutter Click', category: 'foley', duration: 0.4, type: 'camera' },
  { id: 'sfx-glitch', name: 'Digital Glitch Burst', category: 'ui', duration: 0.5, type: 'glitch' },
  { id: 'sfx-bass', name: 'Sub 808 Bass Drop', category: 'cinematic', duration: 1.2, type: 'bass' },
  { id: 'sfx-chime', name: 'Harmonic Triad Chime', category: 'musical', duration: 1.5, type: 'chime' },
  { id: 'sfx-applause', name: 'Crowd Cheers & Applause', category: 'impact', duration: 2.0, type: 'applause' },
];

export const LUT_PRESETS: LutPreset[] = [
  {
    id: 'none',
    name: 'Original',
    previewColor: '#71717a',
    filter: {
      brightness: 0,
      contrast: 0,
      saturation: 0,
      sepia: 0,
      grayscale: 0,
      invert: 0,
      blur: 0,
      hueRotate: 0,
      vignette: 0,
      lutPreset: 'none',
    },
  },
  {
    id: 'cinematic',
    name: 'Teal & Orange',
    previewColor: '#0ea5e9',
    filter: {
      brightness: 5,
      contrast: 25,
      saturation: 20,
      sepia: 15,
      grayscale: 0,
      hueRotate: 345,
      vignette: 35,
      lutPreset: 'cinematic',
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    previewColor: '#d946ef',
    filter: {
      brightness: 10,
      contrast: 35,
      saturation: 45,
      sepia: 0,
      grayscale: 0,
      hueRotate: 290,
      vignette: 45,
      lutPreset: 'cyberpunk',
    },
  },
  {
    id: 'vintage',
    name: 'Retro 1970s Film',
    previewColor: '#d97706',
    filter: {
      brightness: -5,
      contrast: 15,
      saturation: -15,
      sepia: 40,
      grayscale: 0,
      hueRotate: 15,
      vignette: 40,
      lutPreset: 'vintage',
    },
  },
  {
    id: 'noir',
    name: 'Classic B&W Noir',
    previewColor: '#27272a',
    filter: {
      brightness: 0,
      contrast: 40,
      saturation: -100,
      sepia: 0,
      grayscale: 100,
      hueRotate: 0,
      vignette: 55,
      lutPreset: 'noir',
    },
  },
  {
    id: 'sunset',
    name: 'Golden Sunset',
    previewColor: '#f97316',
    filter: {
      brightness: 8,
      contrast: 20,
      saturation: 30,
      sepia: 25,
      grayscale: 0,
      hueRotate: 20,
      vignette: 30,
      lutPreset: 'sunset',
    },
  },
  {
    id: 'vibrant',
    name: 'Vibrant Pop',
    previewColor: '#10b981',
    filter: {
      brightness: 5,
      contrast: 20,
      saturation: 50,
      sepia: 0,
      grayscale: 0,
      hueRotate: 0,
      vignette: 15,
      lutPreset: 'vibrant',
    },
  },
];

export const TEXT_PRESETS: TextPreset[] = [
  {
    id: 'preset-viral-subtitle',
    name: 'TikTok Viral Subtitle',
    category: 'Subtitles',
    data: {
      text: 'VIRAL SUBTITLE HERE',
      fontFamily: 'Montserrat',
      fontSize: 34,
      fontWeight: 800,
      color: '#facc15',
      backgroundColor: '#000000',
      bgPadding: 10,
      textShadow: '0 4px 10px rgba(0,0,0,0.8)',
      animation: 'bounce',
      align: 'center',
      x: 50,
      y: 80,
    },
  },
  {
    id: 'preset-modern-title',
    name: 'Modern Bold Title',
    category: 'Titles',
    data: {
      text: 'CREATIVE DIRECTOR',
      fontFamily: 'Bebas Neue',
      fontSize: 56,
      fontWeight: 700,
      color: '#ffffff',
      backgroundColor: 'transparent',
      textShadow: '0 8px 24px rgba(0,0,0,0.7)',
      animation: 'fade',
      align: 'center',
      x: 50,
      y: 50,
    },
  },
  {
    id: 'preset-cinematic-intro',
    name: 'Cinematic Minimalist',
    category: 'Cinematic',
    data: {
      text: 'THE JOURNEY BEGINS',
      fontFamily: 'Playfair Display',
      fontSize: 38,
      fontWeight: 600,
      color: '#f4f4f5',
      backgroundColor: 'transparent',
      textShadow: '0 4px 16px rgba(0,0,0,0.9)',
      animation: 'fade',
      align: 'center',
      x: 50,
      y: 50,
    },
  },
  {
    id: 'preset-neon-cyber',
    name: 'Neon Cyber Glow',
    category: 'Aesthetic',
    data: {
      text: 'CYBERPUNK 2088',
      fontFamily: 'Syne',
      fontSize: 44,
      fontWeight: 800,
      color: '#00ffff',
      backgroundColor: 'rgba(0,0,0,0.5)',
      bgPadding: 8,
      textShadow: '0 0 20px #00ffff, 0 0 40px #ff007f',
      animation: 'slide-up',
      align: 'center',
      x: 50,
      y: 40,
    },
  },
  {
    id: 'preset-lower-third',
    name: 'News / Lower Third Bar',
    category: 'Lower Thirds',
    data: {
      text: 'BREAKING NEWS: MAJOR UPDATE',
      fontFamily: 'Plus Jakarta Sans',
      fontSize: 26,
      fontWeight: 700,
      color: '#ffffff',
      backgroundColor: '#e11d48',
      bgPadding: 12,
      animation: 'slide-up',
      align: 'left',
      x: 25,
      y: 85,
    },
  },
];

export const STICKER_PACKS = [
  {
    category: 'Social Media',
    stickers: [
      { id: 'stk-sub', badgeType: 'subscribe', label: 'SUBSCRIBE', color: '#e11d48' },
      { id: 'stk-like', badgeType: 'like', label: 'LIKE 👍', color: '#2563eb' },
      { id: 'stk-bell', badgeType: 'bell', label: 'NOTIFY 🔔', color: '#f59e0b' },
      { id: 'stk-verified', badgeType: 'verified', label: 'VERIFIED ✓', color: '#10b981' },
      { id: 'stk-rec', badgeType: 'rec', label: '● REC', color: '#ef4444' },
      { id: 'stk-live', badgeType: 'live', label: 'LIVE STREAM', color: '#dc2626' },
    ],
  },
  {
    category: 'Reactions & Emojis',
    stickers: [
      { id: 'stk-fire', emoji: '🔥', label: 'Fire' },
      { id: 'stk-hundred', emoji: '💯', label: '100%' },
      { id: 'stk-heart', emoji: '❤️', label: 'Heart' },
      { id: 'stk-sparkles', emoji: '✨', label: 'Sparkles' },
      { id: 'stk-rocket', emoji: '🚀', label: 'Rocket' },
      { id: 'stk-eyes', emoji: '👀', label: 'Eyes' },
      { id: 'stk-mindblown', emoji: '🤯', label: 'Mind Blown' },
      { id: 'stk-party', emoji: '🎉', label: 'Party' },
      { id: 'stk-clap', emoji: '👏', label: 'Applause' },
      { id: 'stk-crown', emoji: '👑', label: 'Crown' },
      { id: 'stk-target', emoji: '🎯', label: 'Target' },
      { id: 'stk-star', emoji: '⭐', label: 'Star' },
    ],
  },
];
