import { ApiRequestState, SavedCollection } from './types';

export const SAMPLE_COLLECTIONS: SavedCollection[] = [
  {
    id: 'col_jsonplaceholder',
    name: 'JSONPlaceholder (REST API Demo)',
    description: 'Kumpulan endpoint dummy REST API gratis untuk uji coba GET, POST, query parameters, dan manipulasi data.',
    items: [
      {
        id: 'jp_get_posts',
        name: 'Get All Posts (Limit 5)',
        method: 'GET',
        url: 'https://jsonplaceholder.typicode.com/posts',
        params: [
          { id: 'p1', key: '_limit', value: '5', enabled: true },
          { id: 'p2', key: '_page', value: '1', enabled: true },
        ],
        headers: [
          { id: 'h1', key: 'Accept', value: 'application/json', enabled: true },
        ],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
      {
        id: 'jp_get_single_post',
        name: 'Get Post Detail (ID #1)',
        method: 'GET',
        url: 'https://jsonplaceholder.typicode.com/posts/1',
        params: [],
        headers: [
          { id: 'h1', key: 'Accept', value: 'application/json', enabled: true },
        ],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
      {
        id: 'jp_post_create',
        name: 'Create New Post (POST JSON)',
        method: 'POST',
        url: 'https://jsonplaceholder.typicode.com/posts',
        params: [],
        headers: [
          { id: 'h1', key: 'Content-Type', value: 'application/json; charset=UTF-8', enabled: true },
          { id: 'h2', key: 'Accept', value: 'application/json', enabled: true },
        ],
        auth: { type: 'none' },
        bodyType: 'json',
        rawBody: JSON.stringify(
          {
            title: 'Pengujian API dengan VanPostman Studio',
            body: 'Request berhasil dieksekusi tanpa hambatan CORS berkat Node.js Backend Proxy.',
            userId: 1,
          },
          null,
          2
        ),
        formData: [],
        urlEncodedData: [],
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
      {
        id: 'jp_get_users',
        name: 'List Users Data',
        method: 'GET',
        url: 'https://jsonplaceholder.typicode.com/users',
        params: [],
        headers: [{ id: 'h1', key: 'Accept', value: 'application/json', enabled: true }],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
    ],
  },
  {
    id: 'col_httpbin',
    name: 'HttpBin.org (HTTP Inspection)',
    description: 'Endpoint pengujian standar industri untuk memeriksa header, IP asal, metode HTTP, dan kode status.',
    items: [
      {
        id: 'hb_anything',
        name: 'Echo Anything (Request Inspector)',
        method: 'POST',
        url: 'https://httpbin.org/anything',
        params: [{ id: 'p1', key: 'tool', value: 'postman-tester', enabled: true }],
        headers: [
          { id: 'h1', key: 'Content-Type', value: 'application/json', enabled: true },
          { id: 'h2', key: 'X-Client-Agent', value: 'VanPostman/2.0', enabled: true },
        ],
        auth: { type: 'none' },
        bodyType: 'json',
        rawBody: JSON.stringify(
          {
            app: 'API Tester',
            feature: 'CORS Bypass Proxy',
            testedAt: new Date().toISOString(),
          },
          null,
          2
        ),
        formData: [],
        urlEncodedData: [],
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
      {
        id: 'hb_teapot',
        name: 'Status 418 (I am a Teapot)',
        method: 'GET',
        url: 'https://httpbin.org/status/418',
        params: [],
        headers: [],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
      {
        id: 'hb_headers',
        name: 'View Request Headers',
        method: 'GET',
        url: 'https://httpbin.org/headers',
        params: [],
        headers: [
          { id: 'h1', key: 'X-Custom-Auth', value: 'Token-Secret-12345', enabled: true },
        ],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
    ],
  },
  {
    id: 'col_dummyjson',
    name: 'DummyJSON (E-Commerce & Auth)',
    description: 'API modern mock untuk produk, kutipan, dan simulasi autentikasi token.',
    items: [
      {
        id: 'dj_products',
        name: 'Search Products',
        method: 'GET',
        url: 'https://dummyjson.com/products/search',
        params: [
          { id: 'p1', key: 'q', value: 'phone', enabled: true },
          { id: 'p2', key: 'limit', value: '4', enabled: true },
        ],
        headers: [],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
      {
        id: 'dj_quotes',
        name: 'Get Random Quote',
        method: 'GET',
        url: 'https://dummyjson.com/quotes/random',
        params: [],
        headers: [],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
    ],
  },
  {
    id: 'col_public_apis',
    name: 'Public APIs & Portfolio Backend',
    description: 'Uji endpoint internal server portfolio ini serta API publik dunia nyata.',
    items: [
      {
        id: 'pf_health',
        name: 'Portfolio Backend Health Check',
        method: 'GET',
        url: '/api/health',
        params: [],
        headers: [],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        settings: { bypassCors: true, timeoutMs: 15000, followRedirects: true },
      },
      {
        id: 'pf_articles',
        name: 'Portfolio Articles Feed',
        method: 'GET',
        url: '/api/articles',
        params: [],
        headers: [],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        settings: { bypassCors: true, timeoutMs: 15000, followRedirects: true },
      },
      {
        id: 'pub_github_zen',
        name: 'GitHub Zen (Philosophy of Design)',
        method: 'GET',
        url: 'https://api.github.com/zen',
        params: [],
        headers: [
          { id: 'h1', key: 'User-Agent', value: 'VanPostman-Client', enabled: true },
        ],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        settings: { bypassCors: true, timeoutMs: 20000, followRedirects: true },
      },
      {
        id: 'pub_ip_geo',
        name: 'Public IP & Geo Location (ipapi)',
        method: 'GET',
        url: 'https://ipapi.co/json/',
        params: [],
        headers: [],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        settings: { bypassCors: true, timeoutMs: 20000, followRedirects: true },
      },
    ],
  },
];
