import { WorkspaceProject } from './types';

export const SAMPLE_WORKSPACES: WorkspaceProject[] = [
  {
    id: 'ws_jsonplaceholder',
    name: 'JSONPlaceholder REST API',
    description: 'API publik gratis untuk simulasi RESTful endpoints (Posts, Comments, Users) dengan Swagger 2.0 schema lengkap.',
    swaggerVersion: '2.0',
    info: {
      title: 'JSONPlaceholder REST API Specification',
      version: '1.0.0',
      description: 'Dokumentasi dan pengujian API untuk JSONPlaceholder. Mendukung operasi GET, POST, PUT, DELETE dengan skema tipe parameter dan response standar Swagger 2.0.',
      contact: {
        name: 'Developer Support',
        email: 'dev@jsonplaceholder.typicode.com',
        url: 'https://jsonplaceholder.typicode.com',
      },
      license: {
        name: 'MIT License',
        url: 'https://opensource.org/licenses/MIT',
      },
    },
    host: 'jsonplaceholder.typicode.com',
    basePath: '/',
    schemes: ['https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
      { name: 'Posts', description: 'Operasi untuk mengelola postingan blog' },
      { name: 'Users', description: 'Operasi direktori pengguna' },
      { name: 'Comments', description: 'Operasi komentar pengguna' },
    ],
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 3600000,
    endpoints: [
      {
        id: 'ep_jp_get_posts',
        name: 'Ambil Semua Posts (Pagination)',
        summary: 'Mendapatkan daftar postingan artikel dengan filter limit & halaman',
        description: 'Endpoint ini mengembalikan daftar artikel dalam format array of objects. Mendukung query param `_limit` dan `_page`.',
        operationId: 'getPosts',
        tag: 'Posts',
        method: 'GET',
        url: 'https://jsonplaceholder.typicode.com/posts?_limit=5&_page=1',
        path: '/posts',
        params: [
          {
            id: 'p_limit',
            key: '_limit',
            value: '5',
            enabled: true,
            type: 'integer',
            format: 'int32',
            required: false,
            description: 'Jumlah data per halaman (maksimal 100)',
          },
          {
            id: 'p_page',
            key: '_page',
            value: '1',
            enabled: true,
            type: 'integer',
            format: 'int32',
            required: false,
            description: 'Nomor halaman yang ingin diambil',
          },
        ],
        pathParams: [],
        headers: [
          { id: 'h_acc', key: 'Accept', value: 'application/json', enabled: true, type: 'string' },
        ],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        bodySchema: undefined,
        responses: {
          '200': {
            statusCode: '200',
            description: 'Daftar postingan artikel berhasil didapatkan',
            schemaType: 'array',
            schema: {
              type: 'array',
              itemsType: 'object',
              properties: [],
              itemsProperties: [
                { id: 'f_id', name: 'id', type: 'integer', format: 'int64', description: 'Identifier unik postingan', required: true, example: '1' },
                { id: 'f_uid', name: 'userId', type: 'integer', format: 'int64', description: 'ID pemilik postingan', required: true, example: '1' },
                { id: 'f_title', name: 'title', type: 'string', description: 'Judul artikel', required: true, example: 'sunt aut facere repellat' },
                { id: 'f_body', name: 'body', type: 'string', description: 'Isi lengkap postingan', required: true, example: 'quia et suscipit suscipit recusandae...' },
              ],
            },
            exampleBody: JSON.stringify([
              {
                userId: 1,
                id: 1,
                title: 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
                body: 'quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto',
              },
            ], null, 2),
          },
        },
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
      {
        id: 'ep_jp_get_post_detail',
        name: 'Ambil Detail Post berdasarkan ID',
        summary: 'Mendapatkan data tunggal postingan berdasarkan ID spesifik',
        description: 'Mengembalikan 1 objek artikel. Jika ID tidak ditemukan, mengembalikan status 404.',
        operationId: 'getPostById',
        tag: 'Posts',
        method: 'GET',
        url: 'https://jsonplaceholder.typicode.com/posts/1',
        path: '/posts/{id}',
        params: [],
        pathParams: [
          {
            id: 'pp_id',
            key: 'id',
            value: '1',
            enabled: true,
            type: 'integer',
            format: 'int64',
            required: true,
            location: 'path',
            description: 'ID unik artikel yang dicari',
          },
        ],
        headers: [
          { id: 'h_acc', key: 'Accept', value: 'application/json', enabled: true, type: 'string' },
        ],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        responses: {
          '200': {
            statusCode: '200',
            description: 'Detail artikel ditemukan',
            schema: {
              type: 'object',
              properties: [
                { id: 'f_id', name: 'id', type: 'integer', format: 'int64', required: true, example: '1' },
                { id: 'f_uid', name: 'userId', type: 'integer', format: 'int64', required: true, example: '1' },
                { id: 'f_title', name: 'title', type: 'string', required: true, example: 'sunt aut facere repellat' },
                { id: 'f_body', name: 'body', type: 'string', required: true, example: 'quia et suscipit...' },
              ],
            },
            exampleBody: JSON.stringify({
              userId: 1,
              id: 1,
              title: 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
              body: 'quia et suscipit suscipit recusandae consequuntur expedita et cum',
            }, null, 2),
          },
          '404': {
            statusCode: '404',
            description: 'Postingan dengan ID tersebut tidak ditemukan',
          },
        },
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
      {
        id: 'ep_jp_create_post',
        name: 'Buat Post Baru (POST JSON)',
        summary: 'Membuat rekaman artikel baru dengan body payload JSON',
        description: 'Menerima body request berisi `title`, `body`, dan `userId`. Mengembalikan artikel yang telah dibuat beserta ID baru.',
        operationId: 'createPost',
        tag: 'Posts',
        method: 'POST',
        url: 'https://jsonplaceholder.typicode.com/posts',
        path: '/posts',
        params: [],
        pathParams: [],
        headers: [
          { id: 'h_ct', key: 'Content-Type', value: 'application/json; charset=UTF-8', enabled: true, type: 'string' },
          { id: 'h_acc', key: 'Accept', value: 'application/json', enabled: true, type: 'string' },
        ],
        auth: { type: 'none' },
        bodyType: 'json',
        rawBody: JSON.stringify({
          title: 'Membangun Swagger API Studio',
          body: 'Dokumentasi otomatis dan pengujian live request tanpa hambatan CORS.',
          userId: 1,
        }, null, 2),
        formData: [],
        urlEncodedData: [],
        bodySchema: {
          type: 'object',
          description: 'Payload pembuatan postingan',
          requiredFields: ['title', 'body', 'userId'],
          properties: [
            { id: 'b_title', name: 'title', type: 'string', description: 'Judul artikel postingan baru', required: true, example: 'Judul Baru' },
            { id: 'b_body', name: 'body', type: 'string', description: 'Konten isi postingan', required: true, example: 'Teks artikel lengkap...' },
            { id: 'b_uid', name: 'userId', type: 'integer', format: 'int64', description: 'ID user yang mempublikasikan', required: true, example: '1' },
          ],
        },
        responses: {
          '201': {
            statusCode: '201',
            description: 'Postingan baru berhasil dibuat',
            schema: {
              type: 'object',
              properties: [
                { id: 'r_id', name: 'id', type: 'integer', format: 'int64', required: true, example: '101' },
                { id: 'r_title', name: 'title', type: 'string', required: true, example: 'Membangun Swagger API Studio' },
                { id: 'r_body', name: 'body', type: 'string', required: true, example: 'Dokumentasi otomatis...' },
                { id: 'r_uid', name: 'userId', type: 'integer', required: true, example: '1' },
              ],
            },
            exampleBody: JSON.stringify({
              id: 101,
              title: 'Membangun Swagger API Studio',
              body: 'Dokumentasi otomatis dan pengujian live request tanpa hambatan CORS.',
              userId: 1,
            }, null, 2),
          },
          '400': {
            statusCode: '400',
            description: 'Payload tidak valid atau field wajib belum diisi',
          },
        },
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
      {
        id: 'ep_jp_get_users',
        name: 'Daftar Semua Pengguna',
        summary: 'Mengambil daftar master user beserta alamat dan perusahaan',
        description: 'Daftar profil pengguna lengkap dengan info kontak, geo lat/lng, dan detail company.',
        operationId: 'getUsersList',
        tag: 'Users',
        method: 'GET',
        url: 'https://jsonplaceholder.typicode.com/users',
        path: '/users',
        params: [],
        pathParams: [],
        headers: [
          { id: 'h_acc', key: 'Accept', value: 'application/json', enabled: true, type: 'string' },
        ],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        responses: {
          '200': {
            statusCode: '200',
            description: 'Daftar pengguna berhasil dimuat',
            schemaType: 'array',
            schema: {
              type: 'array',
              itemsType: 'object',
              itemsProperties: [
                { id: 'u_id', name: 'id', type: 'integer', format: 'int64', required: true, example: '1' },
                { id: 'u_name', name: 'name', type: 'string', required: true, example: 'Leanne Graham' },
                { id: 'u_uname', name: 'username', type: 'string', required: true, example: 'Bret' },
                { id: 'u_email', name: 'email', type: 'string', format: 'email', required: true, example: 'Sincere@april.biz' },
                { id: 'u_phone', name: 'phone', type: 'string', example: '1-770-736-8031' },
                { id: 'u_website', name: 'website', type: 'string', example: 'hildegard.org' },
              ],
              properties: [],
            },
          },
        },
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
    ],
  },
  {
    id: 'ws_ecommerce_dummy',
    name: 'E-Commerce Store API',
    description: 'Workspace API untuk Toko Online: Katalog Produk, Kategori, Checkout Keranjang, dan Autentikasi Pelanggan.',
    swaggerVersion: '2.0',
    info: {
      title: 'Store & Commerce API Documentation',
      version: '2.1.0',
      description: 'Spesifikasi REST API lengkap untuk platform e-commerce mencakup katalog produk, inventaris, dan proses pemesanan.',
      contact: {
        name: 'API Gateway Team',
        email: 'api-support@shopdemo.com',
      },
    },
    host: 'dummyjson.com',
    basePath: '/',
    schemes: ['https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
      { name: 'Products', description: 'Pencarian & manajemen katalog produk' },
      { name: 'Carts', description: 'Pengelolaan keranjang belanja' },
      { name: 'Auth', description: 'Autentikasi token JWT' },
    ],
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 7200000,
    endpoints: [
      {
        id: 'ep_shop_products',
        name: 'Cari Produk & Filter Kategori',
        summary: 'Mengambil daftar produk toko dengan pagination dan pencarian',
        description: 'Endpoint ini mendukung parameter query `limit`, `skip`, dan `select` untuk optimasi bandwidth.',
        operationId: 'searchProducts',
        tag: 'Products',
        method: 'GET',
        url: 'https://dummyjson.com/products?limit=6&skip=0',
        path: '/products',
        params: [
          { id: 'sp_limit', key: 'limit', value: '6', enabled: true, type: 'integer', format: 'int32', description: 'Jumlah item per halaman' },
          { id: 'sp_skip', key: 'skip', value: '0', enabled: true, type: 'integer', format: 'int32', description: 'Offset data untuk pagination' },
        ],
        pathParams: [],
        headers: [
          { id: 'h_acc', key: 'Accept', value: 'application/json', enabled: true, type: 'string' },
        ],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        responses: {
          '200': {
            statusCode: '200',
            description: 'Koleksi produk berhasil diambil',
            schema: {
              type: 'object',
              properties: [
                { id: 'pr_total', name: 'total', type: 'integer', format: 'int32', example: '100' },
                { id: 'pr_skip', name: 'skip', type: 'integer', format: 'int32', example: '0' },
                { id: 'pr_limit', name: 'limit', type: 'integer', format: 'int32', example: '6' },
                { id: 'pr_products', name: 'products', type: 'array', description: 'Daftar objek produk' },
              ],
            },
          },
        },
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
      {
        id: 'ep_shop_product_detail',
        name: 'Detail Produk berdasarkan ID',
        summary: 'Informasi lengkap spesifikasi produk dan stok',
        operationId: 'getProductById',
        tag: 'Products',
        method: 'GET',
        url: 'https://dummyjson.com/products/1',
        path: '/products/{id}',
        params: [],
        pathParams: [
          { id: 'p_prod_id', key: 'id', value: '1', enabled: true, type: 'integer', format: 'int64', required: true, location: 'path', description: 'ID produk' },
        ],
        headers: [
          { id: 'h_acc', key: 'Accept', value: 'application/json', enabled: true, type: 'string' },
        ],
        auth: { type: 'none' },
        bodyType: 'none',
        rawBody: '',
        formData: [],
        urlEncodedData: [],
        responses: {
          '200': {
            statusCode: '200',
            description: 'Informasi produk ditemukan',
            schema: {
              type: 'object',
              properties: [
                { id: 'p_id', name: 'id', type: 'integer', example: '1' },
                { id: 'p_title', name: 'title', type: 'string', example: 'Essence Mascara Lash Princess' },
                { id: 'p_price', name: 'price', type: 'number', format: 'float', example: '9.99' },
                { id: 'p_stock', name: 'stock', type: 'integer', example: '5' },
                { id: 'p_rating', name: 'rating', type: 'number', format: 'float', example: '4.94' },
              ],
            },
          },
          '404': {
            statusCode: '404',
            description: 'Produk tidak ditemukan',
          },
        },
        settings: { bypassCors: true, timeoutMs: 30000, followRedirects: true },
      },
    ],
  },
];
