import { FlowchartNode, FlowchartEdge, CanvasDirection } from './types';

export interface FlowchartTemplate {
  id: string;
  title: string;
  category: string;
  description: string;
  direction: CanvasDirection;
  nodes: FlowchartNode[];
  edges: FlowchartEdge[];
}

export const FLOWCHART_TEMPLATES: FlowchartTemplate[] = [
  {
    id: 'oauth-auth-flow',
    title: 'User Authentication & OAuth 2.0 Flow',
    category: 'Security & Auth',
    description: 'Complete user sign-in cycle with credentials, OAuth 2.0 social login, 2FA MFA verification, and JWT session issue.',
    direction: 'TD',
    nodes: [
      {
        id: 'start_user',
        type: 'start',
        label: 'Mulai: Akses Halaman Login',
        description: 'Pengguna membuka web app',
        x: 320,
        y: 60,
        width: 220,
        height: 60,
        bgColor: '#ecfdf5',
        borderColor: '#10b981',
        textColor: '#065f46',
      },
      {
        id: 'input_method',
        type: 'decision',
        label: 'Pilih Metode Login?',
        description: 'OAuth vs Email/Password',
        x: 330,
        y: 170,
        width: 200,
        height: 80,
        bgColor: '#fffbeb',
        borderColor: '#f59e0b',
        textColor: '#92400e',
      },
      {
        id: 'oauth_redirect',
        type: 'process',
        label: 'Redirect ke OAuth Provider',
        description: 'Google / GitHub SSO pop-up',
        x: 80,
        y: 290,
        width: 210,
        height: 65,
        bgColor: '#eff6ff',
        borderColor: '#3b82f6',
        textColor: '#1e40af',
      },
      {
        id: 'input_creds',
        type: 'input',
        label: 'Input Email & Password',
        description: 'Form submission',
        x: 570,
        y: 290,
        width: 200,
        height: 65,
        bgColor: '#f0fdf4',
        borderColor: '#22c55e',
        textColor: '#166534',
      },
      {
        id: 'validate_hash',
        type: 'process',
        label: 'Verifikasi Argon2 Password Hash',
        description: 'Bandingkan hash password di DB',
        x: 570,
        y: 395,
        width: 210,
        height: 65,
        bgColor: '#ffffff',
        borderColor: '#64748b',
        textColor: '#0f172a',
      },
      {
        id: 'check_creds',
        type: 'decision',
        label: 'Kredensial Cocok?',
        description: 'Password valid?',
        x: 580,
        y: 500,
        width: 190,
        height: 80,
        bgColor: '#fffbeb',
        borderColor: '#f59e0b',
        textColor: '#92400e',
      },
      {
        id: 'login_error',
        type: 'end',
        label: 'Tampilkan Pesan Error (401)',
        description: 'Invalid credentials alert',
        x: 840,
        y: 510,
        width: 190,
        height: 60,
        bgColor: '#fef2f2',
        borderColor: '#ef4444',
        textColor: '#991b1b',
      },
      {
        id: 'check_2fa',
        type: 'decision',
        label: '2FA / TOTP Aktif?',
        description: 'Apakah user pasang Google Authenticator?',
        x: 335,
        y: 500,
        width: 190,
        height: 80,
        bgColor: '#fffbeb',
        borderColor: '#f59e0b',
        textColor: '#92400e',
      },
      {
        id: 'input_otp',
        type: 'input',
        label: 'Verifikasi 6-Digit OTP',
        description: 'Validasi token TOTP RFC 6238',
        x: 80,
        y: 510,
        width: 190,
        height: 60,
        bgColor: '#f0fdf4',
        borderColor: '#22c55e',
        textColor: '#166534',
      },
      {
        id: 'issue_jwt',
        type: 'subroutine',
        label: 'Terbitkan JWT Access & Refresh Token',
        description: 'Sign RS256 token & set HttpOnly cookie',
        x: 315,
        y: 630,
        width: 230,
        height: 70,
        bgColor: '#f5f3ff',
        borderColor: '#8b5cf6',
        textColor: '#5b21b6',
      },
      {
        id: 'save_session',
        type: 'database',
        label: 'Simpan Redis Session Cache',
        description: 'Key: session:{userId} TTL: 7 hari',
        x: 325,
        y: 740,
        width: 210,
        height: 65,
        bgColor: '#fdf4ff',
        borderColor: '#a855f7',
        textColor: '#6b21a8',
      },
      {
        id: 'end_success',
        type: 'end',
        label: 'Selesai: Masuk ke Dashboard',
        description: 'Otentikasi sukses 200 OK',
        x: 325,
        y: 845,
        width: 210,
        height: 60,
        bgColor: '#ecfdf5',
        borderColor: '#10b981',
        textColor: '#065f46',
      },
    ],
    edges: [
      { id: 'e1', source: 'start_user', target: 'input_method', style: 'orthogonal', arrowEnd: true },
      { id: 'e2', source: 'input_method', target: 'oauth_redirect', label: 'OAuth SSO', style: 'orthogonal', arrowEnd: true },
      { id: 'e3', source: 'input_method', target: 'input_creds', label: 'Email/Pass', style: 'orthogonal', arrowEnd: true },
      { id: 'e4', source: 'input_creds', target: 'validate_hash', style: 'orthogonal', arrowEnd: true },
      { id: 'e5', source: 'validate_hash', target: 'check_creds', style: 'orthogonal', arrowEnd: true },
      { id: 'e6', source: 'check_creds', target: 'login_error', label: 'Salah', style: 'orthogonal', color: '#ef4444', arrowEnd: true },
      { id: 'e7', source: 'check_creds', target: 'check_2fa', label: 'Cocok', style: 'orthogonal', color: '#10b981', arrowEnd: true },
      { id: 'e8', source: 'oauth_redirect', target: 'check_2fa', label: 'Token Valid', style: 'orthogonal', arrowEnd: true },
      { id: 'e9', source: 'check_2fa', target: 'input_otp', label: 'Ya (Aktif)', style: 'orthogonal', arrowEnd: true },
      { id: 'e10', source: 'input_otp', target: 'issue_jwt', label: 'OTP Valid', style: 'orthogonal', arrowEnd: true },
      { id: 'e11', source: 'check_2fa', target: 'issue_jwt', label: 'Tidak', style: 'orthogonal', arrowEnd: true },
      { id: 'e12', source: 'issue_jwt', target: 'save_session', style: 'orthogonal', arrowEnd: true },
      { id: 'e13', source: 'save_session', target: 'end_success', style: 'orthogonal', arrowEnd: true },
    ],
  },
  {
    id: 'payment-microservice',
    title: 'Payment Gateway & Webhook Architecture',
    category: 'Backend Architecture',
    description: 'High-resilience microservices payment architecture with idempotency keys, payment gateway webhook, and Kafka event streaming.',
    direction: 'LR',
    nodes: [
      {
        id: 'client_app',
        type: 'actor',
        label: 'Client / Mobile App',
        description: 'Kirim POST /checkout',
        x: 60,
        y: 200,
        width: 170,
        height: 65,
        bgColor: '#eff6ff',
        borderColor: '#3b82f6',
        textColor: '#1e40af',
      },
      {
        id: 'api_gw',
        type: 'cloud',
        label: 'API Gateway (Kong / Nginx)',
        description: 'Rate limiting & Auth header check',
        x: 290,
        y: 200,
        width: 190,
        height: 65,
        bgColor: '#f8fafc',
        borderColor: '#64748b',
        textColor: '#0f172a',
      },
      {
        id: 'order_service',
        type: 'process',
        label: 'Order Service',
        description: 'Buat order ID & generate idempotency token',
        x: 540,
        y: 200,
        width: 190,
        height: 65,
        bgColor: '#ffffff',
        borderColor: '#3b82f6',
        textColor: '#0f172a',
      },
      {
        id: 'payment_gw',
        type: 'cloud',
        label: 'Payment Gateway (Stripe / Midtrans)',
        description: 'Charge card / VA / QRIS',
        x: 790,
        y: 200,
        width: 200,
        height: 65,
        bgColor: '#ecfdf5',
        borderColor: '#10b981',
        textColor: '#065f46',
      },
      {
        id: 'webhook_listener',
        type: 'process',
        label: 'Webhook Ingress Listener',
        description: 'Validasi HMAC SHA-256 signature',
        x: 790,
        y: 350,
        width: 200,
        height: 65,
        bgColor: '#fffbeb',
        borderColor: '#f59e0b',
        textColor: '#92400e',
      },
      {
        id: 'kafka_bus',
        type: 'subroutine',
        label: 'Apache Kafka Event Bus',
        description: 'Topic: payment.settled',
        x: 540,
        y: 350,
        width: 190,
        height: 65,
        bgColor: '#f5f3ff',
        borderColor: '#8b5cf6',
        textColor: '#5b21b6',
      },
      {
        id: 'postgres_db',
        type: 'database',
        label: 'PostgreSQL Orders DB',
        description: 'Update status = PAID (ACID transaction)',
        x: 290,
        y: 350,
        width: 190,
        height: 65,
        bgColor: '#fdf4ff',
        borderColor: '#c084fc',
        textColor: '#581c87',
      },
      {
        id: 'notif_service',
        type: 'process',
        label: 'Notification Worker',
        description: 'Kirim email invoice & WhatsApp alert',
        x: 290,
        y: 470,
        width: 190,
        height: 65,
        bgColor: '#ecfdf5',
        borderColor: '#10b981',
        textColor: '#065f46',
      },
    ],
    edges: [
      { id: 'pe1', source: 'client_app', target: 'api_gw', label: '1. Checkout', style: 'orthogonal', arrowEnd: true },
      { id: 'pe2', source: 'api_gw', target: 'order_service', label: '2. Route', style: 'orthogonal', arrowEnd: true },
      { id: 'pe3', source: 'order_service', target: 'payment_gw', label: '3. Charge API', style: 'orthogonal', arrowEnd: true },
      { id: 'pe4', source: 'payment_gw', target: 'webhook_listener', label: '4. HTTP Webhook', style: 'orthogonal', lineStyle: 'dashed', arrowEnd: true },
      { id: 'pe5', source: 'webhook_listener', target: 'kafka_bus', label: '5. Produce Event', style: 'orthogonal', arrowEnd: true },
      { id: 'pe6', source: 'kafka_bus', target: 'postgres_db', label: '6. Update Order', style: 'orthogonal', arrowEnd: true },
      { id: 'pe7', source: 'kafka_bus', target: 'notif_service', label: '7. Notify Customer', style: 'orthogonal', arrowEnd: true },
    ],
  },
  {
    id: 'ai-react-agent',
    title: 'AI Agent ReAct Reasoning & Tool Calling Loop',
    category: 'AI & Machine Learning',
    description: 'Autonomous LLM agent reasoning loop with thought generation, tool execution, memory retrieval, and convergence.',
    direction: 'TD',
    nodes: [
      {
        id: 'agent_input',
        type: 'start',
        label: 'User Query / Objective',
        description: '"Analisis log error dan perbaiki bug"',
        x: 320,
        y: 50,
        width: 220,
        height: 60,
        bgColor: '#ecfdf5',
        borderColor: '#10b981',
        textColor: '#065f46',
      },
      {
        id: 'vector_memory',
        type: 'database',
        label: 'Retrieval: Vector Memory (RAG)',
        description: 'Cari konteks dokumen relevan & chat history',
        x: 320,
        y: 150,
        width: 220,
        height: 65,
        bgColor: '#f5f3ff',
        borderColor: '#8b5cf6',
        textColor: '#5b21b6',
      },
      {
        id: 'llm_reasoning',
        type: 'process',
        label: 'LLM Cognition & Thought Step',
        description: 'Gemini merumuskan rencana & next action',
        x: 320,
        y: 255,
        width: 220,
        height: 65,
        bgColor: '#ffffff',
        borderColor: '#3b82f6',
        textColor: '#0f172a',
      },
      {
        id: 'decision_tool',
        type: 'decision',
        label: 'Perlu Eksekusi Tool?',
        description: 'Apakah butuh API / DB query?',
        x: 330,
        y: 360,
        width: 200,
        height: 80,
        bgColor: '#fffbeb',
        borderColor: '#f59e0b',
        textColor: '#92400e',
      },
      {
        id: 'execute_tool',
        type: 'subroutine',
        label: 'Eksekusi Tool / Function Call',
        description: 'Run SQL query, Web search, Code runner',
        x: 80,
        y: 470,
        width: 210,
        height: 65,
        bgColor: '#eff6ff',
        borderColor: '#3b82f6',
        textColor: '#1e40af',
      },
      {
        id: 'tool_result',
        type: 'input',
        label: 'Ambil Hasil Tool Observation',
        description: 'Inject output kembali ke context window',
        x: 80,
        y: 255,
        width: 210,
        height: 65,
        bgColor: '#f0fdf4',
        borderColor: '#22c55e',
        textColor: '#166534',
      },
      {
        id: 'synthesize_answer',
        type: 'process',
        label: 'Sintesis Jawaban Akhir',
        description: 'Format output markdown & actionable steps',
        x: 320,
        y: 480,
        width: 220,
        height: 65,
        bgColor: '#ffffff',
        borderColor: '#10b981',
        textColor: '#065f46',
      },
      {
        id: 'agent_done',
        type: 'end',
        label: 'Selesai: Respon ke Pengguna',
        description: 'Jawaban final terverifikasi',
        x: 320,
        y: 585,
        width: 220,
        height: 60,
        bgColor: '#ecfdf5',
        borderColor: '#10b981',
        textColor: '#065f46',
      },
    ],
    edges: [
      { id: 'ae1', source: 'agent_input', target: 'vector_memory', style: 'orthogonal', arrowEnd: true },
      { id: 'ae2', source: 'vector_memory', target: 'llm_reasoning', style: 'orthogonal', arrowEnd: true },
      { id: 'ae3', source: 'llm_reasoning', target: 'decision_tool', style: 'orthogonal', arrowEnd: true },
      { id: 'ae4', source: 'decision_tool', target: 'execute_tool', label: 'Ya (Tool Call)', style: 'orthogonal', arrowEnd: true },
      { id: 'ae5', source: 'execute_tool', target: 'tool_result', label: 'Raw Output', style: 'orthogonal', arrowEnd: true },
      { id: 'ae6', source: 'tool_result', target: 'llm_reasoning', label: 'Reflect Loop', style: 'orthogonal', lineStyle: 'dashed', arrowEnd: true },
      { id: 'ae7', source: 'decision_tool', target: 'synthesize_answer', label: 'Tidak (Cukup Data)', style: 'orthogonal', color: '#10b981', arrowEnd: true },
      { id: 'ae8', source: 'synthesize_answer', target: 'agent_done', style: 'orthogonal', arrowEnd: true },
    ],
  },
  {
    id: 'cicd-devops-pipeline',
    title: 'GitOps CI/CD Kubernetes Pipeline',
    category: 'DevOps & Cloud',
    description: 'Automated continuous integration and deployment pipeline with test suites, vulnerability scans, container registry, and ArgoCD rollout.',
    direction: 'LR',
    nodes: [
      {
        id: 'git_push',
        type: 'start',
        label: 'Git Push ke Main Branch',
        description: 'GitHub commit trigger webhook',
        x: 60,
        y: 180,
        width: 190,
        height: 60,
        bgColor: '#ecfdf5',
        borderColor: '#10b981',
        textColor: '#065f46',
      },
      {
        id: 'ci_tests',
        type: 'process',
        label: 'Unit & E2E Test Suite',
        description: 'Vitest, Playwright, TypeScript lint',
        x: 290,
        y: 180,
        width: 190,
        height: 65,
        bgColor: '#ffffff',
        borderColor: '#3b82f6',
        textColor: '#0f172a',
      },
      {
        id: 'test_pass',
        type: 'decision',
        label: 'Semua Test Hijau?',
        description: 'Pass rate = 100%',
        x: 530,
        y: 170,
        width: 180,
        height: 80,
        bgColor: '#fffbeb',
        borderColor: '#f59e0b',
        textColor: '#92400e',
      },
      {
        id: 'notify_fail',
        type: 'end',
        label: 'Kirim Alert Gagal ke Slack',
        description: 'Blokir merge & kirim link log',
        x: 525,
        y: 310,
        width: 190,
        height: 60,
        bgColor: '#fef2f2',
        borderColor: '#ef4444',
        textColor: '#991b1b',
      },
      {
        id: 'docker_build',
        type: 'subroutine',
        label: 'Docker Multi-Stage Build',
        description: 'Compile production image & strip dev dependencies',
        x: 760,
        y: 180,
        width: 210,
        height: 65,
        bgColor: '#eff6ff',
        borderColor: '#3b82f6',
        textColor: '#1e40af',
      },
      {
        id: 'trivy_scan',
        type: 'process',
        label: 'Trivy CVE Security Scan',
        description: 'Cek kerentanan paket OS & CVE Critical',
        x: 1010,
        y: 180,
        width: 200,
        height: 65,
        bgColor: '#ffffff',
        borderColor: '#64748b',
        textColor: '#0f172a',
      },
      {
        id: 'push_registry',
        type: 'cloud',
        label: 'Push ke Google Artifact Registry',
        description: 'Tag: sha-commit & latest',
        x: 1250,
        y: 180,
        width: 210,
        height: 65,
        bgColor: '#f5f3ff',
        borderColor: '#8b5cf6',
        textColor: '#5b21b6',
      },
      {
        id: 'argocd_deploy',
        type: 'end',
        label: 'ArgoCD Sync ke K8s Cluster',
        description: 'Canary rolling update dengan zero downtime',
        x: 1500,
        y: 180,
        width: 220,
        height: 65,
        bgColor: '#ecfdf5',
        borderColor: '#10b981',
        textColor: '#065f46',
      },
    ],
    edges: [
      { id: 'ce1', source: 'git_push', target: 'ci_tests', style: 'orthogonal', arrowEnd: true },
      { id: 'ce2', source: 'ci_tests', target: 'test_pass', style: 'orthogonal', arrowEnd: true },
      { id: 'ce3', source: 'test_pass', target: 'notify_fail', label: 'Gagal', style: 'orthogonal', color: '#ef4444', arrowEnd: true },
      { id: 'ce4', source: 'test_pass', target: 'docker_build', label: 'Lulus (Green)', style: 'orthogonal', color: '#10b981', arrowEnd: true },
      { id: 'ce5', source: 'docker_build', target: 'trivy_scan', style: 'orthogonal', arrowEnd: true },
      { id: 'ce6', source: 'trivy_scan', target: 'push_registry', style: 'orthogonal', arrowEnd: true },
      { id: 'ce7', source: 'push_registry', target: 'argocd_deploy', label: 'GitOps Webhook', style: 'orthogonal', arrowEnd: true },
    ],
  },
  {
    id: 'starter-flow',
    title: 'Clean Minimal Starter',
    category: 'Starter',
    description: 'Simple clean starter flowchart with Start, Input, Process, Decision, and End.',
    direction: 'TD',
    nodes: [
      {
        id: 'start_node',
        type: 'start',
        label: 'Mulai Program',
        description: 'Inisialisasi sistem',
        x: 320,
        y: 80,
        width: 180,
        height: 60,
        bgColor: '#ecfdf5',
        borderColor: '#10b981',
        textColor: '#065f46',
      },
      {
        id: 'input_node',
        type: 'input',
        label: 'Terima Input Data',
        description: 'Parameter masukan',
        x: 320,
        y: 180,
        width: 180,
        height: 65,
        bgColor: '#f0fdf4',
        borderColor: '#22c55e',
        textColor: '#166534',
      },
      {
        id: 'process_node',
        type: 'process',
        label: 'Proses Komputasi',
        description: 'Kalkulasi logika bisnis',
        x: 320,
        y: 285,
        width: 180,
        height: 65,
        bgColor: '#ffffff',
        borderColor: '#3b82f6',
        textColor: '#0f172a',
      },
      {
        id: 'decision_node',
        type: 'decision',
        label: 'Hasil Valid?',
        description: 'Kondisi evaluasi',
        x: 325,
        y: 390,
        width: 170,
        height: 80,
        bgColor: '#fffbeb',
        borderColor: '#f59e0b',
        textColor: '#92400e',
      },
      {
        id: 'end_node',
        type: 'end',
        label: 'Selesai & Cetak Output',
        description: 'Eksekusi tuntas',
        x: 320,
        y: 510,
        width: 180,
        height: 60,
        bgColor: '#ecfdf5',
        borderColor: '#10b981',
        textColor: '#065f46',
      },
    ],
    edges: [
      { id: 'se1', source: 'start_node', target: 'input_node', style: 'orthogonal', arrowEnd: true },
      { id: 'se2', source: 'input_node', target: 'process_node', style: 'orthogonal', arrowEnd: true },
      { id: 'se3', source: 'process_node', target: 'decision_node', style: 'orthogonal', arrowEnd: true },
      { id: 'se4', source: 'decision_node', target: 'end_node', label: 'Ya', style: 'orthogonal', color: '#10b981', arrowEnd: true },
      { id: 'se5', source: 'decision_node', target: 'input_node', label: 'Tidak (Ulangi)', style: 'orthogonal', lineStyle: 'dashed', color: '#ef4444', arrowEnd: true },
    ],
  },
];
