import { PhotoTemplate } from './types';

export const SAMPLE_TEMPLATES: PhotoTemplate[] = [
  {
    id: 'fashion-editorial',
    name: 'Fashion Editorial (Screenshot Default)',
    category: 'Fashion & Style',
    thumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    aspectRatio: '4:3',
    width: 1200,
    height: 900,
    // Stylized orange sunglasses high-fashion model portrait matching user screenshot
    backgroundImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1600&q=85',
    objects: [
      {
        type: 'text',
        text: 'HANDCRAFTING YOUR\nFAVORITE CITY WEAR',
        fontFamily: "'Archivo', sans-serif",
        fontSize: 18,
        fontWeight: '700',
        fontStyle: 'normal',
        fill: '#f4f4f5',
        left: 920,
        top: 60,
        letterSpacing: 80,
        textAlign: 'right',
        opacity: 0.9,
      },
      {
        type: 'text',
        text: 'FASHION',
        fontFamily: "'Archivo', sans-serif",
        fontSize: 140,
        fontWeight: '900',
        fontStyle: 'italic',
        fill: '#ffffff',
        left: 200,
        top: 460,
        letterSpacing: 120,
        textAlign: 'left',
        opacity: 0.95,
        shadow: {
          color: 'rgba(0,0,0,0.35)',
          blur: 20,
          offsetX: 0,
          offsetY: 8,
        },
      },
      {
        type: 'text',
        text: 'F',
        fontFamily: "'Playfair Display', serif",
        fontSize: 160,
        fontWeight: '700',
        fontStyle: 'italic',
        fill: '#ffffff',
        left: 980,
        top: 720,
        textAlign: 'center',
        opacity: 0.95,
      },
    ],
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Tokyo',
    category: 'Futuristic & Street',
    thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    aspectRatio: '16:9',
    width: 1280,
    height: 720,
    backgroundImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1600&q=85',
    objects: [
      {
        type: 'text',
        text: 'NEO TOKYO 2077',
        fontFamily: "'Syne', sans-serif",
        fontSize: 68,
        fontWeight: '800',
        fill: '#00f0ff',
        left: 120,
        top: 320,
        letterSpacing: 100,
        shadow: {
          color: '#00f0ff',
          blur: 25,
          offsetX: 0,
          offsetY: 0,
        },
      },
      {
        type: 'text',
        text: 'AUGMENTED REALITY • DIGITAL HORIZONS',
        fontFamily: "'JetBrains Mono', monospace",
        fontSize: 16,
        fontWeight: '600',
        fill: '#ff0055',
        left: 120,
        top: 410,
        letterSpacing: 60,
      },
    ],
  },
  {
    id: 'minimal-creator',
    name: 'Studio Creator & Portfolio',
    category: 'Minimalist & Clean',
    thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80',
    aspectRatio: '1:1',
    width: 1000,
    height: 1000,
    backgroundImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1400&q=85',
    objects: [
      {
        type: 'text',
        text: 'CRAFTING WITH CODE',
        fontFamily: "'Bebas Neue', sans-serif",
        fontSize: 82,
        fontWeight: '700',
        fill: '#ffffff',
        left: 500,
        top: 500,
        textAlign: 'center',
        letterSpacing: 90,
      },
      {
        type: 'text',
        text: 'Fullstack Architecture & Modern Design',
        fontFamily: "'Plus Jakarta Sans', sans-serif",
        fontSize: 20,
        fontWeight: '500',
        fill: '#cbd5e1',
        left: 500,
        top: 580,
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'sunset-vibes',
    name: 'Golden Hour Aesthetic',
    category: 'Travel & Nature',
    thumbnail: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    aspectRatio: '16:9',
    width: 1200,
    height: 675,
    backgroundImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=85',
    objects: [
      {
        type: 'text',
        text: 'SUMMER ESCAPE',
        fontFamily: "'Cinzel', serif",
        fontSize: 72,
        fontWeight: '800',
        fill: '#fef08a',
        left: 600,
        top: 300,
        textAlign: 'center',
        letterSpacing: 150,
      },
      {
        type: 'text',
        text: 'Discover the unseen architecture of stillness',
        fontFamily: "'Caveat', cursive",
        fontSize: 28,
        fontWeight: '600',
        fill: '#ffffff',
        left: 600,
        top: 390,
        textAlign: 'center',
      },
    ],
  },
];
