import {
  JiraWorkspace,
  JiraProject,
  JiraUser,
  JiraIssue,
  JiraSprint,
  ProjectVersion,
  AutomationRule,
  JiraAuditLog,
  IssueComment,
  WorklogEntry,
} from './types';

export const INITIAL_MEMBERS: JiraUser[] = [
  {
    id: 'user-irvan',
    name: 'Muchamad Irvan',
    email: 'vanviolet.js@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    role: 'admin',
    title: 'Lead Architect & Staff Engineer',
  },
  {
    id: 'user-sarah',
    name: 'Sarah Jenkins',
    email: 'sarah.j@nexuscorp.internal',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    role: 'lead',
    title: 'Senior Frontend Engineer',
  },
  {
    id: 'user-alex',
    name: 'Alex Rivera',
    email: 'alex.r@nexuscorp.internal',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    role: 'member',
    title: 'Distributed Systems Engineer',
  },
  {
    id: 'user-maya',
    name: 'Maya Putri',
    email: 'maya.p@nexuscorp.internal',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    role: 'member',
    title: 'Lead Product Manager',
  },
  {
    id: 'user-david',
    name: 'David Chen',
    email: 'david.c@nexuscorp.internal',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    role: 'member',
    title: 'DevOps & Site Reliability Engineer',
  },
];

export const INITIAL_WORKSPACE: JiraWorkspace = {
  id: 'ws-nexus-eng',
  name: 'Nexus Engineering Core',
  slug: 'nexus-eng',
  description: 'Enterprise Cloud Architecture & Distributed Systems Workspace',
  ownerEmail: 'vanviolet.js@gmail.com',
  createdAt: '2026-08-01T08:00:00Z',
  members: INITIAL_MEMBERS,
};

export const INITIAL_PROJECTS: JiraProject[] = [
  {
    id: 'proj-nex',
    key: 'NEX',
    name: 'Nexus Cloud Platform',
    description: 'High-throughput microservices platform, OAuth SSO, and low-latency event broker.',
    leadId: 'user-irvan',
    template: 'scrum',
    category: 'Software Development',
    avatar: '⚡',
    createdAt: '2026-08-05T09:00:00Z',
    customFields: [
      { id: 'cf-env', name: 'Environment', type: 'select', options: ['Development', 'Staging', 'Production'] },
      { id: 'cf-risk', name: 'Risk Level', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { id: 'cf-repro', name: 'Reproduction Steps', type: 'text' },
    ],
    columns: [
      { status: 'todo', name: 'To Do', color: 'bg-stone-500/10 text-stone-700 dark:text-stone-300' },
      { status: 'in_progress', name: 'In Progress', limit: 4, color: 'bg-blue-500/10 text-blue-700 dark:text-blue-300' },
      { status: 'in_review', name: 'Code Review', limit: 3, color: 'bg-amber-500/10 text-amber-700 dark:text-amber-300' },
      { status: 'qa', name: 'QA & Testing', limit: 3, color: 'bg-purple-500/10 text-purple-700 dark:text-purple-300' },
      { status: 'done', name: 'Done', color: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300' },
    ],
  },
  {
    id: 'proj-mob',
    key: 'MOB',
    name: 'Mobile Client Application',
    description: 'Native iOS & Android client with biometric unlock and offline synchronization.',
    leadId: 'user-sarah',
    template: 'kanban',
    category: 'Mobile Applications',
    avatar: '📱',
    createdAt: '2026-08-15T10:00:00Z',
    customFields: [
      { id: 'cf-os', name: 'Operating System', type: 'select', options: ['iOS', 'Android', 'Both'] },
    ],
    columns: [
      { status: 'todo', name: 'Backlog', color: 'bg-stone-500/10 text-stone-700 dark:text-stone-300' },
      { status: 'in_progress', name: 'Developing', limit: 5, color: 'bg-blue-500/10 text-blue-700 dark:text-blue-300' },
      { status: 'in_review', name: 'PR Review', color: 'bg-amber-500/10 text-amber-700 dark:text-amber-300' },
      { status: 'done', name: 'Released', color: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300' },
    ],
  },
];

export const INITIAL_SPRINTS: JiraSprint[] = [
  {
    id: 'sprint-14',
    projectId: 'proj-nex',
    name: 'Sprint 14 - Platform Hardening',
    goal: 'Ship OAuth2 refresh tokens, resolve Redis locking race condition, and finalize v2.4 Release Candidate.',
    startDate: '2026-09-07T00:00:00Z',
    endDate: '2026-09-21T23:59:59Z',
    status: 'active',
    committedPoints: 26,
    completedPoints: 11,
    velocityPoints: 24,
  },
  {
    id: 'sprint-15',
    projectId: 'proj-nex',
    name: 'Sprint 15 - Edge Acceleration',
    goal: 'Introduce distributed edge proxy caching and WebSocket multiplexing for sub-10ms response times.',
    startDate: '2026-09-22T00:00:00Z',
    endDate: '2026-10-06T23:59:59Z',
    status: 'future',
    committedPoints: 18,
    completedPoints: 0,
    velocityPoints: 22,
  },
  {
    id: 'sprint-13',
    projectId: 'proj-nex',
    name: 'Sprint 13 - Database Optimization',
    goal: 'Partition high-write telemetry tables and implement connection pooling.',
    startDate: '2026-08-24T00:00:00Z',
    endDate: '2026-09-06T23:59:59Z',
    status: 'closed',
    completedAt: '2026-09-06T18:30:00Z',
    committedPoints: 24,
    completedPoints: 24,
    velocityPoints: 24,
  },
];

export const INITIAL_VERSIONS: ProjectVersion[] = [
  {
    id: 'ver-2-4',
    projectId: 'proj-nex',
    name: 'v2.4.0',
    description: 'Enterprise SSO, sliding session tokens, and security audits.',
    releaseDate: '2026-09-25T00:00:00Z',
    status: 'unreleased',
    featuresCount: 6,
    bugsFixedCount: 4,
  },
  {
    id: 'ver-2-3',
    projectId: 'proj-nex',
    name: 'v2.3.0',
    description: 'PostgreSQL partitioning, KaTeX rendering pipeline, and dynamic rate limiting.',
    releaseDate: '2026-09-05T00:00:00Z',
    status: 'released',
    featuresCount: 8,
    bugsFixedCount: 5,
  },
];

export const INITIAL_ISSUES: JiraIssue[] = [
  // Epics
  {
    id: 'issue-nex-1',
    key: 'NEX-1',
    projectId: 'proj-nex',
    title: 'Core Authentication & Multi-Tenancy Architecture',
    description: 'End-to-end OAuth2/OIDC integration, tenant isolation, and cryptographically verified JWT tokens.',
    type: 'epic',
    status: 'in_progress',
    priority: 'highest',
    assigneeId: 'user-irvan',
    reporterId: 'user-maya',
    labels: ['security', 'auth', 'architecture'],
    components: ['Auth Service', 'Gateway'],
    startDate: '2026-09-01T00:00:00Z',
    dueDate: '2026-09-30T00:00:00Z',
    createdAt: '2026-09-01T09:00:00Z',
    updatedAt: '2026-09-12T14:20:00Z',
    subtasks: [],
    linkedIssues: [],
    attachments: [],
    commentsCount: 3,
    timeSpentMinutes: 720,
    order: 1,
  },
  {
    id: 'issue-nex-2',
    key: 'NEX-2',
    projectId: 'proj-nex',
    title: 'Low-Latency Event Streaming Broker',
    description: 'High-throughput publish-subscribe message pipeline supporting 50,000+ simultaneous WebSocket streams.',
    type: 'epic',
    status: 'todo',
    priority: 'high',
    assigneeId: 'user-alex',
    reporterId: 'user-irvan',
    labels: ['performance', 'realtime'],
    components: ['Broker', 'WebSockets'],
    startDate: '2026-09-15T00:00:00Z',
    dueDate: '2026-10-15T00:00:00Z',
    createdAt: '2026-09-02T10:00:00Z',
    updatedAt: '2026-09-10T11:00:00Z',
    subtasks: [],
    linkedIssues: [],
    attachments: [],
    commentsCount: 1,
    timeSpentMinutes: 0,
    order: 2,
  },

  // Sprint 14 Issues
  {
    id: 'issue-nex-101',
    key: 'NEX-101',
    projectId: 'proj-nex',
    title: 'Implement JWT key rotation with sliding session renewals',
    description: `### Acceptance Criteria:
- Use RS256 with dual public keys during active rotation windows.
- Background worker must gracefully re-sign session tokens without dropping user state.
- Fallback token verification must complete in under 5ms.`,
    type: 'story',
    status: 'in_progress',
    priority: 'highest',
    epicId: 'issue-nex-1',
    sprintId: 'sprint-14',
    assigneeId: 'user-irvan',
    reporterId: 'user-maya',
    storyPoints: 5,
    originalEstimateMinutes: 480,
    remainingEstimateMinutes: 180,
    timeSpentMinutes: 300,
    labels: ['jwt', 'security', 'backend'],
    components: ['Auth Service'],
    dueDate: '2026-09-18T18:00:00Z',
    createdAt: '2026-09-07T10:00:00Z',
    updatedAt: '2026-09-13T06:30:00Z',
    subtasks: [
      { id: 'st-1', key: 'NEX-101-1', title: 'Generate asymmetric key pair generator script', completed: true, assigneeId: 'user-irvan' },
      { id: 'st-2', key: 'NEX-101-2', title: 'Add Redis key registry with 24-hour expiration', completed: true, assigneeId: 'user-irvan' },
      { id: 'st-3', key: 'NEX-101-3', title: 'Write integration test verifying zero-downtime rotation', completed: false, assigneeId: 'user-irvan' },
    ],
    linkedIssues: [
      { id: 'l-1', type: 'blocks', targetIssueKey: 'NEX-104', targetIssueTitle: 'Design organization-level RBAC schema' }
    ],
    attachments: [
      {
        id: 'att-1',
        name: 'jwt-rotation-flowchart.png',
        size: 245760,
        type: 'image/png',
        url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&auto=format&fit=crop&q=80',
        uploadedAt: '2026-09-08T11:00:00Z',
        uploadedBy: 'Muchamad Irvan',
      }
    ],
    commentsCount: 2,
    versionId: 'ver-2-4',
    order: 1,
  },
  {
    id: 'issue-nex-102',
    key: 'NEX-102',
    projectId: 'proj-nex',
    title: 'Fix race condition in distributed Redis lock manager',
    description: `Concurrent transactions attempting to acquire the distributed mutex during failover cause stale state write collisions.
    
**Stack trace:**
\`\`\`
RedlockAcquireError: Failed to obtain lock on 3 of 5 nodes within 200ms
  at Redlock.acquire (services/lockManager.ts:44)
\`\`\``,
    type: 'bug',
    status: 'in_progress',
    priority: 'highest',
    sprintId: 'sprint-14',
    assigneeId: 'user-alex',
    reporterId: 'user-david',
    storyPoints: 8,
    originalEstimateMinutes: 600,
    remainingEstimateMinutes: 240,
    timeSpentMinutes: 360,
    labels: ['bug', 'redis', 'concurrency'],
    components: ['Data Layer'],
    dueDate: '2026-09-16T17:00:00Z',
    createdAt: '2026-09-08T14:30:00Z',
    updatedAt: '2026-09-12T16:00:00Z',
    subtasks: [
      { id: 'st-4', key: 'NEX-102-1', title: 'Reproduce with 100 concurrent workers', completed: true, assigneeId: 'user-alex' },
      { id: 'st-5', key: 'NEX-102-2', title: 'Implement fencing token algorithm', completed: false, assigneeId: 'user-alex' },
    ],
    linkedIssues: [],
    attachments: [],
    commentsCount: 4,
    versionId: 'ver-2-4',
    order: 2,
  },
  {
    id: 'issue-nex-103',
    key: 'NEX-103',
    projectId: 'proj-nex',
    title: 'Setup Prometheus metrics exporter for Redis clusters',
    description: 'Export real-time cache hit ratios, command latencies, and memory fragmentation metrics to Grafana dashboard.',
    type: 'task',
    status: 'todo',
    priority: 'medium',
    sprintId: 'sprint-14',
    assigneeId: 'user-david',
    reporterId: 'user-irvan',
    storyPoints: 3,
    originalEstimateMinutes: 240,
    remainingEstimateMinutes: 240,
    timeSpentMinutes: 0,
    labels: ['devops', 'monitoring', 'grafana'],
    components: ['Infrastructure'],
    dueDate: '2026-09-20T17:00:00Z',
    createdAt: '2026-09-09T09:15:00Z',
    updatedAt: '2026-09-09T09:15:00Z',
    subtasks: [],
    linkedIssues: [],
    attachments: [],
    commentsCount: 0,
    versionId: 'ver-2-4',
    order: 3,
  },
  {
    id: 'issue-nex-104',
    key: 'NEX-104',
    projectId: 'proj-nex',
    title: 'Design organization-level RBAC permission matrix',
    description: 'Support custom role definitions (Owner, Admin, Lead, Member, Auditor) with granular feature toggles.',
    type: 'story',
    status: 'in_review',
    priority: 'high',
    epicId: 'issue-nex-1',
    sprintId: 'sprint-14',
    assigneeId: 'user-sarah',
    reporterId: 'user-maya',
    storyPoints: 5,
    originalEstimateMinutes: 360,
    remainingEstimateMinutes: 60,
    timeSpentMinutes: 300,
    labels: ['rbac', 'security', 'frontend'],
    components: ['Web Console'],
    dueDate: '2026-09-17T18:00:00Z',
    createdAt: '2026-09-08T10:00:00Z',
    updatedAt: '2026-09-13T04:10:00Z',
    subtasks: [
      { id: 'st-6', key: 'NEX-104-1', title: 'Define TypeScript permission enums', completed: true, assigneeId: 'user-sarah' },
      { id: 'st-7', key: 'NEX-104-2', title: 'Build interactive permission matrix table', completed: true, assigneeId: 'user-sarah' },
    ],
    linkedIssues: [
      { id: 'l-2', type: 'is_blocked_by', targetIssueKey: 'NEX-101', targetIssueTitle: 'Implement JWT key rotation' }
    ],
    attachments: [],
    commentsCount: 3,
    versionId: 'ver-2-4',
    order: 4,
  },
  {
    id: 'issue-nex-105',
    key: 'NEX-105',
    projectId: 'proj-nex',
    title: 'Deploy edge worker reverse proxy with HTTP/3 & TLS 1.3',
    description: 'Configure automated certificate renewal, Brotli compression, and regional routing via Cloudflare/Fastly.',
    type: 'task',
    status: 'done',
    priority: 'medium',
    sprintId: 'sprint-14',
    assigneeId: 'user-david',
    reporterId: 'user-irvan',
    storyPoints: 3,
    originalEstimateMinutes: 180,
    remainingEstimateMinutes: 0,
    timeSpentMinutes: 180,
    resolvedAt: '2026-09-12T16:45:00Z',
    resolution: 'Done',
    labels: ['devops', 'edge', 'tls'],
    components: ['Infrastructure'],
    createdAt: '2026-09-07T08:00:00Z',
    updatedAt: '2026-09-12T16:45:00Z',
    subtasks: [],
    linkedIssues: [],
    attachments: [],
    commentsCount: 1,
    versionId: 'ver-2-4',
    order: 5,
  },
  {
    id: 'issue-nex-107',
    key: 'NEX-107',
    projectId: 'proj-nex',
    title: 'Security audit on OAuth redirect URI validations',
    description: 'Ensure exact regex matching on redirect_uri parameters to prevent open redirect and token leakage vulnerabilities.',
    type: 'bug',
    status: 'qa',
    priority: 'high',
    epicId: 'issue-nex-1',
    sprintId: 'sprint-14',
    assigneeId: 'user-irvan',
    reporterId: 'user-david',
    storyPoints: 5,
    originalEstimateMinutes: 300,
    remainingEstimateMinutes: 60,
    timeSpentMinutes: 240,
    labels: ['security', 'audit', 'oauth'],
    components: ['Auth Service'],
    dueDate: '2026-09-16T12:00:00Z',
    createdAt: '2026-09-10T11:00:00Z',
    updatedAt: '2026-09-13T05:00:00Z',
    subtasks: [],
    linkedIssues: [],
    attachments: [],
    commentsCount: 2,
    versionId: 'ver-2-4',
    order: 6,
  },

  // Sprint 15 Issues (Future Sprint)
  {
    id: 'issue-nex-106',
    key: 'NEX-106',
    projectId: 'proj-nex',
    title: 'Migrate WebSocket connection pool to Epoll native bindings',
    description: 'Switch from standard Node.js event emitter to uWebSockets.js for 10x throughput and memory efficiency.',
    type: 'story',
    status: 'todo',
    priority: 'high',
    epicId: 'issue-nex-2',
    sprintId: 'sprint-15',
    assigneeId: 'user-alex',
    reporterId: 'user-irvan',
    storyPoints: 8,
    originalEstimateMinutes: 480,
    remainingEstimateMinutes: 480,
    timeSpentMinutes: 0,
    labels: ['websockets', 'performance', 'c++'],
    components: ['Broker'],
    createdAt: '2026-09-11T14:00:00Z',
    updatedAt: '2026-09-11T14:00:00Z',
    subtasks: [],
    linkedIssues: [],
    attachments: [],
    commentsCount: 0,
    order: 1,
  },

  // Backlog Issues (Not in any sprint)
  {
    id: 'issue-nex-108',
    key: 'NEX-108',
    projectId: 'proj-nex',
    title: 'Add dark mode theme export for custom analytical dashboards',
    description: 'Allow users to export custom high-contrast color palettes for Wallboard TV displays.',
    type: 'story',
    status: 'todo',
    priority: 'low',
    reporterId: 'user-sarah',
    storyPoints: 3,
    labels: ['ui', 'theme'],
    components: ['Web Console'],
    createdAt: '2026-09-11T16:00:00Z',
    updatedAt: '2026-09-11T16:00:00Z',
    subtasks: [],
    linkedIssues: [],
    attachments: [],
    commentsCount: 0,
    order: 1,
  },
  {
    id: 'issue-nex-109',
    key: 'NEX-109',
    projectId: 'proj-nex',
    title: 'GraphQL batch mutation rate limiter & cost calculation',
    description: 'Compute AST query complexity before execution and throttle requests exceeding 1000 complexity points/sec.',
    type: 'task',
    status: 'todo',
    priority: 'medium',
    reporterId: 'user-irvan',
    storyPoints: 5,
    labels: ['graphql', 'rate-limit'],
    components: ['Gateway'],
    createdAt: '2026-09-12T09:00:00Z',
    updatedAt: '2026-09-12T09:00:00Z',
    subtasks: [],
    linkedIssues: [],
    attachments: [],
    commentsCount: 0,
    order: 2,
  },
];

export const INITIAL_COMMENTS: IssueComment[] = [
  {
    id: 'comm-1',
    issueId: 'issue-nex-101',
    authorId: 'user-irvan',
    authorName: 'Muchamad Irvan',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    content: 'Initial benchmarks show token verification overhead dropped from 4.2ms to 0.8ms using in-memory LRU key caching.',
    createdAt: '2026-09-11T10:15:00Z',
  },
  {
    id: 'comm-2',
    issueId: 'issue-nex-101',
    authorId: 'user-sarah',
    authorName: 'Sarah Jenkins',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    content: '@Muchamad Irvan looks good! The web client handles the refresh token rotation seamlessly on 401 response interceptors.',
    createdAt: '2026-09-12T11:40:00Z',
  },
  {
    id: 'comm-3',
    issueId: 'issue-nex-102',
    authorId: 'user-alex',
    authorName: 'Alex Rivera',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    content: 'Root cause confirmed: The TTL expiration jitter on replica nodes allowed two clients to simultaneously claim lock acquisition. Patch in progress with fencing tokens.',
    createdAt: '2026-09-11T17:30:00Z',
  },
];

export const INITIAL_WORKLOGS: WorklogEntry[] = [
  {
    id: 'wl-1',
    issueId: 'issue-nex-101',
    authorId: 'user-irvan',
    authorName: 'Muchamad Irvan',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    timeSpentMinutes: 180,
    description: 'Implemented asymmetric key pair generator and Redis TTL registry.',
    loggedAt: '2026-09-10T15:00:00Z',
  },
  {
    id: 'wl-2',
    issueId: 'issue-nex-101',
    authorId: 'user-irvan',
    authorName: 'Muchamad Irvan',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    timeSpentMinutes: 120,
    description: 'Integrated sliding token renewal handler into Express middleware.',
    loggedAt: '2026-09-12T14:30:00Z',
  },
  {
    id: 'wl-3',
    issueId: 'issue-nex-102',
    authorId: 'user-alex',
    authorName: 'Alex Rivera',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    timeSpentMinutes: 360,
    description: 'Chaos testing with 100 concurrent threads reproducing Redlock race condition.',
    loggedAt: '2026-09-11T16:00:00Z',
  },
];

export const INITIAL_AUTOMATIONS: AutomationRule[] = [
  {
    id: 'auto-1',
    projectId: 'proj-nex',
    name: 'Auto-transition Parent to Code Review when Sub-tasks are Done',
    description: 'When all child sub-tasks of a Story are marked complete, automatically move the Story to In Review.',
    enabled: true,
    trigger: 'subtask_completed',
    condition: 'All sub-tasks completed',
    action: 'Set status to In Review',
    executionCount: 14,
    lastExecutedAt: '2026-09-12T16:45:00Z',
  },
  {
    id: 'auto-2',
    projectId: 'proj-nex',
    name: 'Critical Priority Alert & Auto-assign',
    description: 'When an issue priority is set to Highest, tag with label "urgent" and assign to Project Lead.',
    enabled: true,
    trigger: 'priority_changed',
    condition: 'Priority == Highest',
    action: 'Add label "urgent" & notify team lead',
    executionCount: 7,
    lastExecutedAt: '2026-09-10T11:20:00Z',
  },
  {
    id: 'auto-3',
    projectId: 'proj-nex',
    name: 'Set Resolution Date on Completion',
    description: 'When an issue is moved to Done column, timestamp resolvedAt and calculate lead time.',
    enabled: true,
    trigger: 'status_changed',
    condition: 'Status == Done',
    action: 'Set resolvedAt to now()',
    executionCount: 42,
    lastExecutedAt: '2026-09-12T16:45:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: JiraAuditLog[] = [
  {
    id: 'audit-1',
    projectId: 'proj-nex',
    issueKey: 'NEX-105',
    actorName: 'David Chen',
    actorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    action: 'Completed task NEX-105',
    details: 'Moved status from QA to Done',
    timestamp: '2026-09-12T16:45:00Z',
  },
  {
    id: 'audit-2',
    projectId: 'proj-nex',
    issueKey: 'NEX-104',
    actorName: 'Sarah Jenkins',
    actorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    action: 'Ready for Review',
    details: 'Moved status from In Progress to In Review',
    timestamp: '2026-09-12T15:20:00Z',
  },
  {
    id: 'audit-3',
    projectId: 'proj-nex',
    issueKey: 'NEX-101',
    actorName: 'Muchamad Irvan',
    actorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    action: 'Logged 2h work',
    details: 'Updated remaining estimate to 3h',
    timestamp: '2026-09-12T14:30:00Z',
  },
];

export const initialJiraState = {
  workspace: INITIAL_WORKSPACE,
  projects: INITIAL_PROJECTS,
  issues: INITIAL_ISSUES,
  sprints: INITIAL_SPRINTS,
  members: INITIAL_MEMBERS,
  versions: INITIAL_VERSIONS,
  automations: INITIAL_AUTOMATIONS,
  auditLogs: INITIAL_AUDIT_LOGS,
};
